// Firebase client config via compile-time --dart-define (see app/.env.example).
// Native Android/iOS files are generated by app/scripts/write_firebase_native_config.*
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

String _requireDefine(String name) {
  final value = String.fromEnvironment(name);
  if (value.isEmpty) {
    throw StateError(
      'Missing compile-time define $name. '
      'Local: flutter run --dart-define-from-file=.env (copy from .env.example). '
      'CI: set repository secrets and run scripts/write_firebase_native_config before build.',
    );
  }
  return value;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _requireDefine('FIREBASE_ANDROID_API_KEY'),
        appId: _requireDefine('FIREBASE_ANDROID_APP_ID'),
        messagingSenderId: _requireDefine('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _requireDefine('FIREBASE_PROJECT_ID'),
        storageBucket: _requireDefine('FIREBASE_STORAGE_BUCKET'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _requireDefine('FIREBASE_IOS_API_KEY'),
        appId: _requireDefine('FIREBASE_IOS_APP_ID'),
        messagingSenderId: _requireDefine('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _requireDefine('FIREBASE_PROJECT_ID'),
        storageBucket: _requireDefine('FIREBASE_STORAGE_BUCKET'),
        iosClientId: _requireDefine('FIREBASE_IOS_CLIENT_ID'),
        iosBundleId: _requireDefine('FIREBASE_IOS_BUNDLE_ID'),
      );
}
